### ISSUE TITLE
Replace Rockchain with Ixxo

### ISSUE THREAD

**Issue by markhahnel** [genomesio/genomes#25]
Throrughout site - Replace all mentions of Rockchain with Ixxo  - All urls should point to https://ixxo.io/

Rockchain logo to be replaced with Ixxo logo and link to https://www.google.co.uk/search?q=ixxo+logo&tbm=isch&source=iu&ictx=1&fir=9XJiOLU0yAnrdM%253A%252CIh9w44LetklnaM%252C_&usg=AI4_-kSGEPYvHwwURslFlZFlVN6T381LQQ&sa=X&ved=2ahUKEwi4sdKZheXdAhVMdcAKHQiGAysQ9QEwCHoECAYQFA#imgrc=9XJiOLU0yAnrdM:

**Comment by ilirhushi** [comment]
@markhahnel we need clarification for @Edmondi-Kacaj question
