### ISSUE TITLE
footer - buy genome sequenced

### ISSUE THREAD

**Issue by genomeschris** [genomesio/genomes#49]
change to - 'Order a Kit'

**Comment by ilirhushi** [comment]
@axhem Have a look on these changes:

5 columns - left to right 

Column 1
No change needed

Column 2
How it works - links to how it works page
Register Kit and Byuy Genome sequence - light grey - non clickable

Column 3
Remove Partner 1,2,3,4,5 - Add a line that says get in touch, clicking opens mail with info@genomes.io

Column 4
Ethereum - link to https://www.ethereum.org/
Replace Rockchain with Ixxo - link to https://ixxo.io/
Remove Medical Professionals/Educators/Scientists


Column 5
Add twitter = twitter.com/genomesio
